name: wq_ml
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aom=3.12.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freeglut=3.8.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2025.0.0
  - joblib=1.5.2
  - jpeg=9f
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libavif=1.3.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libglib=2.84.4
  - libhwloc=2.12.1
  - libiconv=1.16
  - libkrb5=1.21.3
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libpq=17.6
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - numexpr=2.14.1
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openssl=3.0.18
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pyparsing=3.2.5
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - seaborn=0.13.2
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - sqlite=3.51.0
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - catboost==1.2.8
      - colorama==0.4.6
      - formulaic==1.2.1
      - graphviz==0.21
      - interface-meta==1.3.0
      - lifelines==0.30.0
      - mapie==1.2.0
      - narwhals==2.13.0
      - ngboost==0.5.8
      - plotly==6.5.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - wrapt==2.0.1
prefix: C:\Users\ansle\anaconda3\envs\wq_ml
